version: "2"
checks:
  method-count:
    config:
      threshold: 25
  method-complexity:
    config:
      threshold: 10
plugins:
  sonar-java:
    enabled: true
    config:
      sonar.java.source: "11"
      tests_patterns:
        - src/test/**
  fixme:
    enabled: true
  markdownlint:
    enabled: true
    checks:
      MD013:
        enabled: false
  checkstyle:
    enabled: true
    config:
      file: "checkstyle.xml"